fix build with glibc 2.34; rel 2
unistd.h is now included indirectly causing signature conflict:

profiles/audio/media.c:1284:13: error: conflicting types for 'pause'; have '_Bool(void *)'
 1284 | static bool pause(void *user_data)
      |             ^~~~~
In file included from /usr/include/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /usr/include/glib-2.0/glib/gbacktrace.h:36,
                 from /usr/include/glib-2.0/glib.h:34,
                 from profiles/audio/media.c:21:
/usr/include/unistd.h:489:12: note: previous declaration of 'pause' with type 'int(void)'
  489 | extern int pause (void);
      |            ^~~~~